### ISSUE TITLE
Can't get screen share audio to work

### ISSUE THREAD

**Issue by SandWoodJones** [Vencord/venmic#28]
### ✍️ Bug Description

I first encountered this while trying to get Discord to work on NixOS. I kinda gave up on that system and tried a new EndeavourOS installation. I'm using KDE Plasma 6.1 wayland.
Installing Vesktop and sharing the screen works fine but the streams have no audio. In truth, I'm getting the same result i was getting on NixOS.

### 🔁 Steps to reproduce

1. Install the Vesktop AppImage
2. Join a discord call (in this case i used a second account to test the stream audio)
3. Open a youtube video in firefox
4. Stream the firefox window
5. There is no sound.

### 🗒️ Debug Output

[venmic.log](https://github.com/user-attachments/files/17007378/venmic.log)

### ❔ Expected behavior

The screen share audio to work and me being able to hear the youtube video from my other account.

### 📦 Vesktop Version

1.5.3

### 🖥️ Distribution

EndeavourOS

### ✅ I confirm that...

- [X] I have collected all the required information and read all the comments in this document
- [X] I searched for an existing bug report for this issue
- [X] the problem does occur with the reproduction steps I provided

**Comment by Curve** [comment]
It seems your target application is not playing to the default speaker but the venmic settings are set to ignore such nodes.

Please also share your audio screenshare settings (found in the screenshare modal) and try adjusting them appropriately.

**Comment by Curve** [comment]
Also, I'm not sure if I just can't find it on my phones display, but Venmic never actually received the command (from vesktop) to share audio from any node

**Comment by Curve** [comment]
It seems like you did not select the desired audio source to share (There is no link request sent from Vesktop as evident in the logs).

Just so that we're on the same page, you need to select the desired audio source, it should look roughly like this in the screenshare modal:

![image](https://github.com/user-attachments/assets/dad7a6e0-cd30-41aa-b941-7d5a1412838e)
![image](https://github.com/user-attachments/assets/e0928302-1243-49e1-bb94-c660d8f972c5)

The venmic settings are available in the screenshare modal as well and there are some settings you might want to toggle off (this is only a quick guess from the venmic log provided):

![image](https://github.com/user-attachments/assets/83cd72fc-d2fe-43b7-b392-1fdd8fa9ac63)
![image](https://github.com/user-attachments/assets/1718788c-7716-4925-a1e1-802b8aa2d55a)

You might have to tweak these settings depending on your audio setup, in case the application you want to share plays to a speaker that is not your default speaker you might want to turn off the highlighted setting.

All toggles have descriptions that should help you to find the right ones in case you have an "unusual" audio setup.

**Comment by SandWoodJones** [comment]
Thanks for the quick support. I really did forget to set up the audio sources. To my defense I didn't notice there was a scrollbar 😅​
![image](https://github.com/user-attachments/assets/1bd56ecb-8ebe-46b9-92bc-cd5d17cb4162)

**Comment by Curve** [comment]
> Thanks for the quick support. I really did forget to set up the audio sources. To my defense I didn't notice there was a scrollbar 😅​
> ![image](https://github.com/user-attachments/assets/1bd56ecb-8ebe-46b9-92bc-cd5d17cb4162)
> 

Oh, that is really well hidden on smaller displays :'D

Maybe we can do something to increase the visibility here, but that would be a Vesktop issue :D
